### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by h-2** [leafac/shiki-latex#1]
Thanks for providing this tool and for suggesting it over at minted.

However, the following example:

```tex
\documentclass{scrartcl}

\usepackage{realboxes}
\usepackage{fontspec}

\newfontfamily\UbuntuMono{Ubuntu Mono}
\setmonofont{Ubuntu Mono}

\usepackage[table,svgnames]{xcolor} 
\definecolor{lightgrey}{rgb}{0.9,0.9,0.9}
\definecolor{dsolar_back}{HTML}{FDF6E3}
\definecolor{dsolar_text}{HTML}{657B83}
\definecolor{teal}{HTML}{94ccbe}

\usepackage[letterspace=60]{microtype}

\usepackage{minted}

\setminted[c++]{
    linenos=true,
    bgcolor=dsolar_back,
    fontsize=\footnotesize,
    style=solarizedlight,
    frame=single,
    framesep=5pt,
    rulecolor=\color{lightgrey},
    stepnumber=2,
    numbersep=5pt,
    stripnl=false,
}

% Fix the frame overlapping the background
\makeatletter
\renewenvironment{minted@colorbg}[1]{
\setlength{\fboxsep}{\z@}
\def\minted@bgcol{#1}
\noindent
\begin{lrbox}{\minted@bgbox}
\begin{minipage}{\linewidth}}
{\end{minipage}
\end{lrbox}%
\colorbox{\minted@bgcol}{\usebox{\minted@bgbox}}}
\makeatother


\renewcommand\theFancyVerbLine{{\color{dsolar_text}\small\arabic{FancyVerbLine}}}

\renewcommand{\MintedPygmentize}{/usr/home/hannes/node_modules/.bin/shiki-minted}

\begin{document}
\begin{minted}{c++}
gapped<dna15> v;                    // gapped<T> is a typedef for alphabet_variant<T, gap>

static_assert(alphabet_size<gapped<dna15>>  == 16);  // alphabet size is 15 + 1
static_assert(sizeof(gapped<dna15>)         == 1);   // memory size is 1 byte

v = 'C'_dna15;                      // assign from one alternative type
std::cout << v.to_char();           // prints 'C'
v = 'A'_rna15;                      // implicitly converts to 'A'_dna15 and assigns that
std::cout << v.to_char();           // prints 'A'
v = gap{};                          // assign from the other alternative type
std::cout << v.to_char();           // prints '-'

v.assign_char('G');                 // character results in state belonging to dna15
std::cout << v.to_char();           // prints 'G'
std::cout << (v == gap{});          // false, because not in gap-state

dna15 d = v.convert_to<dna15>();    // successful
//gap g = v.convert_to<gap>();      // would throw an exception because v is in dna15-state
v.assign_char('-');                 // in gap state
gap   g = v.convert_to<gap>();      // successful
\end{minted}

\end{document}
```

Fails to build with the following error:
```
(/usr/local/share/texmf-dist/tex/latex/microtype/mt-LatinModernRoman.cfg)(node:6623) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '-P'
    at Object.openSync (fs.js:457:3)
    at Object.readFileSync (fs.js:359:35)
    at /usr/home/hannes/node_modules/shiki-latex/lib/shiki-minted.js:28:40
(node:6623) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6623) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.141 \end{minted}
```

**Comment by h-2** [comment]
This is texlive-2015 (I know it's old, but FreeBSD doesn't have anything newer). I suspect that that is using pygmentize's  `-P` and not `-O` and shiki-latex can't handle that?

**Comment by leafac** [comment]
Thanks for the bug report and for the detailed investigation. I released a new version (1.0.1) that should fix your issue. Please run the following and then try to compile your LaTeX document:

```console
$ npm update shiki-latex
```

**Comment by h-2** [comment]
Yes, this fixes, it thanks! Results look mostly better than pygments, but not always. I guess C++ is just super-difficult to parse. I am still playing around with themes.

**Comment by leafac** [comment]
If the colors look different than what you see in Visual Studio Code, then please add to [this conversation](https://github.com/octref/shiki/issues/30). If the colors also look wrong in Visual Studio Code, then you can try to fix things [there](https://github.com/microsoft/vscode/tree/master/extensions/cpp/syntaxes) as well.
